#######################################################################################
# Book settings
title : PseudoLab Applied AI 스터디
author: PseudoLab
logo: 'PseudoLab_logo.png'
copyright: "2023"

# Short description about the book
description: >-
  Basic Jupyter Book template for PseudoLab studies

#######################################################################################
# Execution settings
execute:
  execute_notebooks           : off

#######################################################################################
# HTML-specific settings
html:
  home_page_in_navbar         : false

# #######################################################################################
# Interact link settings
notebook_interface            : "notebook"

#######################################################################################
# Launch button settings
repository:
  url                         : https://github.com/Pseudo-Lab/applied-ai/
  path_to_book                : "book"

latex:
  latex_engine                : "xelatex"
  latex_documents:
    targetname: book.tex
    
html:
  favicon: 'PseudoLab_logo.png'
  use_issues_button: true
  use_repository_button: true
  google_analytics_id: G-H5EKC658P6
  
sphinx:
  config:
    html_js_files:
    - https://cdnjs.cloudflare.com/ajax/libs/require.js/2.3.4/require.min.js